spring:
  application:
    name: algo_lens
  config:
    import: optional:classpath:application-secret.yml

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

  cache:
    type: redis
    redis:
      time-to-live: 300000

  profiles:
   active: local


logging:
  level:
    org.springframework.cache: TRACE
    io.netty.resolver.dns.DnsServerAddressStreamProviders: OFF








