spring:
  application:
    name: algo_lens
  config:
    import: optional:application-secret.yml

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true
